plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-slate
sidebar:
  - terms
# AirPod Case
---
id: terms
---
## Terms
#### "AirPods" Refers to the earbuds.
#### "Shell" Refers to the container that hold the AirPods.
#### "Case" Refers to the thing that protects the Shell and inturn also the AirPods.

## Problem Statement
#### - You cannot check the battery percent of your AirPods without the use of a phone. The people who identify this as a problem are non-iPhone users and students. The environment in which this occurs is at school or a busy setting. This problem has been occurring since Apple released AirPods. According to the poll I created, 88% of the 30 students I polled agree that this is a problem they have.

## Marketplace Research
### Research Summary Sheet:
#### Snyder, B. (2023, January 29). How to check airpods battery levels on Android. ScreenRant. https://screenrant.com/check-airpods-battery-levels-android-how/

#### G., A. (2023, June 26). How to check airpods’ battery on Android phones [Ultimate Guide]. Headphonesty. https://www.headphonesty.com/2022/08/check-airpods-battery-on-android/ 

#### Khan, Z. (2024, August 26). How to check your airpods battery status. SoundGuys. https://www.soundguys.com/how-to-check-airpods-battery-status-67235/ 

#### Stockton, B. (2024, February 27). How to check airpods battery levels on Android. groovyPost. https://www.groovypost.com/howto/check-airpods-battery-levels-on-android/ 

#### Joseph, M. (2022, August 11). How to check airpods battery on Android. Stealth Optional. https://stealthoptional.com/article/how-to-check-airpods-battery-on-android 

#### Costello, S. (2023, November 1). How to check your airpods battery status. Lifewire. https://www.lifewire.com/check-airpods-battery-status-7570322 

#### Staff, B. (2023, April 17). How to check airpods battery level. https://beebom.com/how-check-airpods-battery-level/ 

#### Régo , N. (2018, February 12). How to check airpods’ battery life on an Android device. COOL BLIND TECH. https://coolblindtech.com/how-to-check-airpods-battery-life-on-an-android-device/ 

#### Makohon, A. (2024, March 2). How to check airpods battery: Unveiling the secrets of airpods battery life - treblab blog. TREBLAB. https://treblab.com/blogs/news/how-to-check-airpod-battery 

### Artifact Summary
#### Android users need to use a third party app to be able to see the battery % of there AirPods. 
#### This helps further the fact that there is a problem with being able to check the battery of AirPods









## Sources
#### - [AirPod Poll](https://docs.google.com/forms/d/1aVDSOM6HkFfgVF3ke4yvM-jfQLU2wg3XL9RGB56SbAs/prefill)
